import { useTableReducer } from './hooks/useTableReducer';
import type { TInitialState, TActios } from './hooks/useTableReducer';
import CustomReactTable from './CustomReactTable';
import Pagination from './TableComponents/Pagination';
import { useGridMetaData } from './ArrangeView/utils';
export * from 'src/components/CustomReactTable/hooks/useColumnsReactTable';
export default CustomReactTable;
export { useTableReducer, Pagination, useGridMetaData };
export type { TInitialState, TActios };
export * from './utils';
export * from './hooks/hookUtils';
