import { ColumnDef } from '@tanstack/react-table';

export type InitialState<D> = {
  columns: Column<D>[];
  pivotColumn: Column<D>;
};

export type Column<D> = {
  _id?: string;
  id?: string;
  lockPosition?: boolean;
  fieldName?: string;
  fieldLabel?: string;
  required?: boolean;
  unique?: boolean;
  type?: string;
  isTooltip?: boolean;
  order?: number;
  editAble?: boolean;
  disableOnEdit?: boolean;
  hiddenField?: boolean;
  isDropdown?: boolean;
  isWarningTooltip?: boolean;
  lookup?: boolean;
  lookupResource?: string;
  warningTooltipMessage?: string;
  primaryField?: boolean;
  resource?: 'Opportunity';
  brand?: '630dbe1e9ec418610523529c';
  roleType?: number;
  dataList?: boolean;
  dataListId?: string;
  entityWiseLookup?: boolean;
  formula?: string;
  formulaFields?: any[];
  formulainputFields?: any[];
  htmlDescription?: string;
  inputFields?: any[];
  isColumnEditable?: boolean;
  isFieldEntityWise?: boolean;
  isHideColumnSum?: boolean;
  isMinMaxValue?: boolean;
  isSystemGenerate?: boolean;
  isUneditable?: boolean;
  maxValue?: number;
  maxValueServiceAdd?: string;
  minValue?: number;
  minValueServiceAdd?: string;
  preFilters?: any[];
  showInPdf?: boolean;
  stopHideColumn?: boolean;
  subFields?: any[];
  systemGeneratedPrefix?: string;
  visibilityCondition?: any[];
  columnSize?: number;
  counterFieldInputFields?: any[];
  dateValidation?: any[];
  enableServicesAddOnBasedOnValue?: boolean;
  lookupPreFilterFields?: any[];
  operationOnLineItems?: string;
  requiredDependentOn?: any[];
  restrictBackDate?: boolean;
  restrictCurrentDateAutoSelect?: boolean;
  restrictFutureDate?: boolean;
  servicesAddOnBasedOnValue?: any[];
  showTotalInCard?: boolean;
  currency?: 'USD';
  accessorKey?: string;
  accessor?: string;
  minWidth?: number;
  width?: number;
  show?: boolean;
  decimalPlaces?: number;
  disabled?: boolean;
  editable?: boolean;
  option?: Option[];
  tooltipMessage?: string;
  deletAble?: boolean;
  addManualOptionInExcel?: boolean;
  addAdditionalOption?: boolean;
  disableFilters?: boolean;
  addBulkOptions?: boolean;
  disableSortBy?: boolean;
  lookupDependentOn?: string;
  showAdditionalInfoPopup?: boolean;
  isDependentDropdown?: boolean;
  dropdowDependentOn?: string;
  size?: number;
  minSize?: number;
  sticky?: string;
  canDrag?: boolean;
} & ColumnDef<D>;

export type DefaultValue = '' | 'New';

export type Option = {
  optionLabel?: string;
  optionValue?: string;
  order?: number;
  default?: boolean;
  id?: number;
  outcome?: string;
};
