export type ColumnData = {
  fieldName: string;
  fieldLabel: string;
  resource: string;
  type: string;
  order: number;
  required?: boolean;
  _id?: string;
  option?: Option[];
  isTooltip?: boolean;
  tooltipMessage?: string;
  editAble?: boolean;
  hiddenField?: boolean;
  isDefaultValue?: boolean;
  disableOnEdit?: boolean;
  addAdditionalOption?: boolean;
  defaultValue?: string;
  lookup?: boolean;
  lookupResource?: string;
  sectionName?: string;
  brand?: string;
  roleType?: number;
  addManualOptionInExcel?: boolean;
  entityWiseLookup?: boolean;
  isColumnEditable?: boolean;
  isDropdown?: boolean;
  isHideColumnSum?: boolean;
  isMinMaxValue?: boolean;
  isSystemGenerate?: boolean;
  isWarningTooltip?: boolean;
  lookupDependentOn?: string;
  lookupDependentOnField?: string;
  maxValue?: number;
  maxValueServiceAdd?: string;
  minValue?: number;
  minValueServiceAdd?: string;
  warningTooltipMessage?: string;
  addBulkOptions?: boolean;
  columnSize?: number;
  dataList?: boolean;
  dataListId?: string;
  formula?: string;
  formulaFields?: any[];
  formulainputFields?: any[];
  formulaoption?: Formulaoption;
  htmlDescription?: string;
  inputFields?: any[];
  isFieldEntityWise?: boolean;
  preFilters?: any[];
  showInPdf?: boolean;
  stopHideColumn?: boolean;
  subFields?: any[];
  visibilityCondition?: any[];
  lookupPreFilterFields?: any[];
  sectionProperties?: Formulaoption;
};

export type Formulaoption = {};

export type Option = {
  optionLabel: string;
  optionValue: string;
  order: number;
  default: boolean;
};
