export const SET_USER = "SET_USER";
export const SET_ROLE = "SET_ROLE";
export const USER_LOADING = "SET_USER_LOADING";
export const SET_SELECTED_ENTITY = "SET_SELECTED_ENTITY"
export const SET_CHATTER = "SET_CHATTER"
export const SET_CART_COUNT = "SET_CART_COUNT"
export const SET_START_TOUR = "SET_START_TOUR"
export const SET_GRID_METADATA = "SET_GRID_METADATA"

