const DefaultFields = [
    // {
    //     _id: "1",
    //     fieldName: 'qty',
    //     fieldLabel: 'Qty',
    //     required: true,
    //     type: 'decimal',
    //     decimalPlaces: 2,
    //     sectionName: 'Cost Calculation',
    //     isTooltip: false,
    //     order: 1,
    //     editAble: false,
    // },
    //Cost Calculation    
    {
        _id: "2",
        fieldName: 'totalCostPerUnit',
        fieldLabel: 'Total Cost Per Unit',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Cost Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 1,
        editAble: false,
        displayCurrency: ["USD"]
    },
    {
        _id: "3",
        fieldName: 'totalCost',
        fieldLabel: 'Total Cost',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Cost Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 2,
        editAble: false,
        displayCurrency: ["USD"],
        isFormula: true,
        formula: "return qty * totalCostPerUnit_usd",
        inputFields: ["qty", "totalCostPerUnit_usd"],
        returnType: "decimal",
        decimalPlaces: 2
    },
    //Cost Calculation  
    {
        _id: "4",
        fieldName: 'marginPerUnit',
        fieldLabel: 'Margin Per Unit',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Sales Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 3,
        editAble: false,
        displayCurrency: ["USD"],
        isMulitFormula: true,
        formulaFields: ["marginPercentPerUnit"],
        formulainputFields: ["totalCostPerUnit_usd", "marginPerUnit_usd"],
        formulaoption: { marginPercentPerUnit: "return marginPerUnit_usd * 100 / totalCostPerUnit_usd" },
        isDefaultValue: true,
        defaultValue: "0"
    },
    {
        _id: "5",
        fieldName: 'marginPercentPerUnit',
        fieldLabel: 'Margin Percent Per Unit',
        required: true,
        type: 'percent',
        sectionName: 'Sales Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 4,
        editAble: false,
        isMulitFormula: true,
        formulaFields: ["marginPerUnit_usd"],
        formulainputFields: ["totalCostPerUnit_usd", "marginPercentPerUnit"],
        formulaoption: { marginPerUnit_usd: "return totalCostPerUnit_usd * marginPercentPerUnit / 100" },
        isDefaultValue: true,
        defaultValue: "0"
    },
    {
        _id: "6",
        fieldName: 'commissionPerUnit',
        fieldLabel: 'Commission Per Unit',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Sales Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 5,
        editAble: false,
        displayCurrency: ["USD"],
        isMulitFormula: true,
        formulaFields: ["commissionPercentPerUnit"],
        formulainputFields: ["totalCostPerUnit_usd", "commissionPerUnit_usd"],
        formulaoption: { commissionPercentPerUnit: "return commissionPerUnit_usd * 100 / totalCostPerUnit_usd " },
        isDefaultValue: true,
        defaultValue: "0"
    },
    {
        _id: "7",
        fieldName: 'commissionPercentPerUnit',
        fieldLabel: 'Commission Percent Per Unit',
        required: true,
        type: 'percent',
        sectionName: 'Sales Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 6,
        editAble: false,
        isMulitFormula: true,
        formulaFields: ["commissionPerUnit_usd"],
        formulainputFields: ["totalCostPerUnit_usd", "commissionPercentPerUnit"],
        formulaoption: { commissionPerUnit_usd: "return totalCostPerUnit_usd * commissionPercentPerUnit / 100 " },
        isDefaultValue: true,
        defaultValue: "0"
    },
    {
        _id: "9",
        fieldName: 'profitPerUnit',
        fieldLabel: 'Profit Per Unit',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Sales Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 7,
        editAble: false,
        displayCurrency: ["USD"],
        isMulitFormula: true,
        formulaFields: ["salesPricePerUnit_usd", "profitPercentPerUnit"],
        formulainputFields: ["totalCostPerUnit_usd", "profitPerUnit_usd", "marginPerUnit_usd", "commissionPerUnit_usd"],
        formulaoption: {
            salesPricePerUnit_usd: "return  totalCostPerUnit_usd + marginPerUnit_usd + commissionPerUnit_usd + profitPerUnit_usd",
            profitPercentPerUnit: "return (profitPerUnit_usd * 100) /  (totalCostPerUnit_usd + marginPerUnit_usd + commissionPerUnit_usd)"
        },
        isDefaultValue: true,
        defaultValue: "0"
    },
    {
        _id: "10",
        fieldName: 'profitPercentPerUnit',
        fieldLabel: 'Profit Percent Per Unit',
        required: true,
        type: 'percent',
        sectionName: 'Sales Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 8,
        editAble: false,
        isMulitFormula: true,
        formulaFields: ["profitPerUnit_usd"],
        formulainputFields: ["totalCostPerUnit_usd", "marginPerUnit_usd", "commissionPerUnit_usd", "profitPercentPerUnit"],
        formulaoption: {
            profitPerUnit_usd: "return ((totalCostPerUnit_usd + marginPerUnit_usd + commissionPerUnit_usd ) * profitPercentPerUnit) / 100",
        },
        isDefaultValue: true,
        defaultValue: "0"
    },
    {
        _id: "8",
        fieldName: 'salesPricePerUnit',
        fieldLabel: 'Sales Price Per Unit',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Sales Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 9,
        editAble: false,
        displayCurrency: ["USD"],
        isFormula: true,
        formula: "return totalCostPerUnit_usd + marginPerUnit_usd + commissionPerUnit_usd + profitPerUnit_usd",
        inputFields: ["totalCostPerUnit_usd", "marginPerUnit_usd", "commissionPerUnit_usd", "profitPerUnit_usd"],
        returnType: "decimal",
        decimalPlaces: 2,
        isMulitFormula: true,
        formulaFields: ["profitPerUnit_usd", "profitPercentPerUnit"],
        formulainputFields: ["salesPricePerUnit_usd", "totalCostPerUnit_usd", "marginPerUnit_usd", "commissionPerUnit_usd"],
        formulaoption: {
            profitPerUnit_usd: "return salesPricePerUnit_usd -   (totalCostPerUnit_usd + marginPerUnit_usd + commissionPerUnit_usd)",
            profitPercentPerUnit: "return (salesPricePerUnit_usd -  (totalCostPerUnit_usd + marginPerUnit_usd + commissionPerUnit_usd)) * 100 / (totalCostPerUnit_usd + marginPerUnit_usd + commissionPerUnit_usd)"
        },
        isDefaultValue: true,
        defaultValue: "0"
    },
    {
        _id: "11",
        fieldName: 'totalSalesPrice',
        fieldLabel: 'Total Sales Price',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Total Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 10,
        editAble: false,
        displayCurrency: ["USD"],
        isFormula: true,
        formula: "return qty * salesPricePerUnit_usd",
        inputFields: ["qty", "salesPricePerUnit_usd"],
        returnType: "decimal",
        decimalPlaces: 2,
        isDefaultValue: true,
        defaultValue: "0",
        isUneditable: true,
    },
    {
        _id: "14",
        fieldName: 'totalMargin',
        fieldLabel: 'Total Margin',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Total Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 11,
        editAble: false,
        displayCurrency: ["USD"],
        isFormula: true,
        formula: "return qty * marginPerUnit_usd",
        inputFields: ["qty", "marginPerUnit_usd"],
        returnType: "decimal",
        decimalPlaces: 2,
        isDefaultValue: true,
        defaultValue: "0",
        isUneditable: true,
    }, {
        _id: "13",
        fieldName: 'totalCommission',
        fieldLabel: 'Total Commission',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Total Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 12,
        editAble: false,
        displayCurrency: ["USD"],
        isFormula: true,
        formula: "return qty * commissionPerUnit_usd",
        inputFields: ["qty", "commissionPerUnit_usd"],
        returnType: "decimal",
        decimalPlaces: 2,
        isDefaultValue: true,
        defaultValue: "0",
        isUneditable: true,
    },
    {
        _id: "12",
        fieldName: 'totalProfit',
        fieldLabel: 'Total Profit',
        required: true,
        type: 'currencyAmount',
        sectionName: 'Total Price Calculation',
        sectionType: 'cost',
        isTooltip: false,
        order: 13,
        editAble: false,
        displayCurrency: ["USD"],
        isFormula: true,
        formula: "return qty * profitPerUnit_usd",
        inputFields: ["qty", "profitPerUnit_usd"],
        returnType: "decimal",
        decimalPlaces: 2,
        isDefaultValue: true,
        defaultValue: "0",
        isUneditable: true,
    },
]

export default DefaultFields;
