name: Deploy to EKS

on:
  push:
    branches:
      - uat
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::194722417414:role/GitHubActionsEKSRole
          aws-region: us-east-2

      - name: 'Login to Amazon ECR'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Env Secrets
        id: secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: ENV_SECRETS, ${{vars.AWS_SECRET_ARN}}

      - name: 'Build and Push Image to ECR'
        if: success()
        id: build
        env:
          CONTAINER_PREFIX: ${{ vars.CONTAINER_PREFIX }}
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$CONTAINER_PREFIX-$TIMESTAMP
          IMAGE_URI_LATEST=$ECR_REGISTRY/$ECR_REPOSITORY:$CONTAINER_PREFIX-latest
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
          echo "$ENV_SECRETS" >> .env
          # Build the Docker image
          docker build -t $IMAGE_URI  -t $IMAGE_URI_LATEST .
          # Push the Docker image to ECR
          docker push $IMAGE_URI
          docker push "$IMAGE_URI_LATEST"

      - name: 'Deploy to EKS'
        if: success()
        env:
          DEPLOYMENT_NAME: ${{vars.DEPLOYMENT_NAME}}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
        run: |
          # Update kubeconfig
          aws eks update-kubeconfig \
            --region ${AWS_REGION} \
            --name ${EKS_CLUSTER_NAME}
          # Update the deployment
          kubectl set image deployment/${DEPLOYMENT_NAME} frontend=${IMAGE_URI}
